### ISSUE TITLE
Уметь запускать npm start из произвольного каталога

### ISSUE THREAD

**Issue by ovcharenko-di** [ovcharenko-di/1coverage#16]
обнаружил ошибку в команде start

если выполнять ее в произвольном каталоге, то прокси не стартует, т.к. в этом каталоге отсутствует package.json

варианты решения:
- копировать package.json в произвольный каталог
- устанавливать правильный рабочий каталог для консольной команды npm start
- указывать путь к package.json (если это возможно)

**Comment by asosnoviy** [comment]
Использовать exe

**Comment by ovcharenko-di** [comment]
исправлено
